# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-2019'

steps:
- task: DownloadSecureFile@1
  inputs:
    secureFile: 'assistantSMS.env.dart'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'ls'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'mv ./assistantSMS.env.dart ./lib/env.dart'

- task: FlutterInstall@0
  inputs:
    mode: 'auto'
    channel: 'stable'
    version: 'latest'

- task: FlutterCommand@0
  inputs:
    projectDirectory: '.'
    arguments: 'config --enable-web'

- task: FlutterCommand@0
  inputs:
    projectDirectory: '.'
    arguments: 'build web -t lib/prod.dart --release'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: './build/web'
    ArtifactName: 'flutterWeb'
    publishLocation: 'Container'

    
