# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-2019'

steps:
- task: FlutterInstall@0
  inputs:
    mode: 'auto'
    channel: 'stable'
    version: 'latest'

- task: CmdLine@2
  inputs:
    script: '$(FlutterToolPath)/flutter config --enable-web'

- task: FlutterBuild@0
  inputs:
    target: 'apk'
    projectDirectory: '.'
    apkTargetPlatform: 'custom'
    customApkTargetPlatform: 'web'
    entryPoint: 'lib/prod.dart'
    dartDefine: '--release'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: './build/web'
    ArtifactName: 'flutterWeb'
    publishLocation: 'Container'

    
