name: scrapmechanic_kurtlourens_com
description: A companion app for Scrap Mechanic.
publish_to: 'none'
version: 1.11.0+55 # dart scripts\version_num_script.dart

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: 1.0.5

  # AssistantApps
  assistantapps_flutter_common:
    git: https://github.com/AssistantApps/Flutter.Common.git
    # path: 'C:\Development\Projects\AssistantApps\assistantapps_flutter_common'

  # Trouble makers
  firebase_core: 2.4.1
  firebase_analytics: 10.1.0
  firebase_analytics_web: 0.5.1+8

  # UI
  adaptive_theme: 3.4.1
  avatar_glow: 3.0.1
  bitsdojo_window: 0.1.5
  breakpoint: 1.2.0
  country_icons: 2.0.2
  dartx: 1.1.0
  dotted_border: 2.1.0
  floating_bottom_navigation_bar: 1.5.2
  fluro: 2.0.5
  flutter_redux: 0.10.0
  flutter_simple_treeview: 3.0.2
  get_it: 7.6.4
  redux: 5.0.0
  rflutter_alert: 2.0.7
  step_progress_indicator: 1.0.2
  universal_html: 2.2.4

dev_dependencies:
  flutter_launcher_icons: 0.11.0
  pubspec_parse: 1.2.3
  git: 2.2.1

dependency_overrides:
  http: 1.1.2
  intl: 0.18.0

flutter_icons: ## flutter pub run flutter_launcher_icons:main
  ios: true
  android: true
  image_path: 'assets/img/fullSizeIcon.png'
  adaptive_icon_background: 'assets/img/fullSizeIconAdaptiveBg.png'
  adaptive_icon_foreground: 'assets/img/fullSizeIconAdaptiveFg.png'

# flutter pub run msix:create
msix_config: # https://pub.dev/documentation/msix/latest/
  display_name: Assistant for Scrap Mechanic
  publisher_display_name: AssistantApps
  msix_version: 1.11.0.0
  identity_name:
  publisher: 
  logo_path: './assets/images/fullSizeIcon.png'
  languages: en
  capabilities: internetClient
  store: true

flutter:
  uses-material-design: true

  assets:
    - assets/data/ # Data files
    - assets/data/whatIsNew/ # What Is New Data files
    - assets/lang/ # Languages

    # Images
    - assets/img/
    - assets/img/donation/
    - assets/img/drawer/
    - assets/img/items/
    - assets/img/raid/
    - assets/img/rating/dark/
    - assets/img/rating/light/
    - assets/img/tile/

    # Base Json Items
    - assets/json/
    - assets/json/de/
    - assets/json/en/
    - assets/json/es/
    - assets/json/fr/
    - assets/json/it/
    - assets/json/ja/
    - assets/json/ko/
    - assets/json/po/
    - assets/json/pt-br/
    - assets/json/ru/
    - assets/json/zh-hans/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto/Roboto-Light.ttf
