name: scrapmechanic_kurtlourens_com
description: A companion app for Scrap Mechanic.
publish_to: 'none'
version: 1.6.0+42

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: 1.0.3

  # AssistantApps
  assistantapps_flutter_common: 
    git: https://github.com/AssistantApps/Flutter.Common.git
    # path: 'C:\Development\Projects\AssistantApps\assistantapps_flutter_common'

  # Firebase
  firebase_core: 1.5.0
  firebase_analytics: 8.3.0
  firebase_analytics_web: 0.3.0+1

  # Redux
  flutter_redux: 0.8.2
  redux: 5.0.0

  # UI
  country_icons: 2.0.2
  custom_navigation_bar: 0.8.2
  dotted_border: 2.0.0+1
  flash: 2.0.1
  flutter_simple_treeview: 3.0.0-nullsafety.1
  flutter_staggered_grid_view: 0.4.0
  giffy_dialog: 1.8.0
  rflutter_alert: 2.0.4
  step_progress_indicator: 1.0.1
  theme_mode_handler: 3.0.0

  # Base
  get_it: 7.2.0
  fluro: 2.0.3
  dartx: 0.7.1

  # Misc
  breakpoint: 1.2.0
  logger: 1.0.0
  share: 2.0.4 # Move to AA?
  shared_preferences: 2.0.6
  shared_preferences_web: 2.0.1
  universal_html: 2.0.8

dev_dependencies:
  flutter_launcher_icons: 0.9.0
  # flutter_test:
  #   sdk: flutter  

# dependency_overrides:
#   intl: ^0.17.0-nullsafety.2
# #   firebase_core: 0.7.0

flutter_icons:
  ios: true
  android: true
  image_path: "assets/img/fullSizeIcon.png"
  adaptive_icon_background: "assets/img/fullSizeIconAdaptiveBg.png"
  adaptive_icon_foreground: "assets/img/fullSizeIconAdaptiveFg.png"

flutter:
  uses-material-design: true
  
  assets:
    - assets/data/ # Data files
    - assets/data/whatIsNew/ # What Is New Data files
    - assets/lang/ # Languages
    
    # Images
    - assets/img/ 
    - assets/img/donation/
    - assets/img/drawer/
    - assets/img/items/
    - assets/img/raid/
    - assets/img/rating/dark/
    - assets/img/rating/light/
    - assets/img/tile/

    # Base Json Items
    - assets/json/ 
    - assets/json/de/
    - assets/json/en/
    - assets/json/es/
    - assets/json/fr/
    - assets/json/it/
    - assets/json/ja/
    - assets/json/ko/
    - assets/json/po/
    - assets/json/pt-br/
    - assets/json/ru/
    - assets/json/zh-hans/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto/Roboto-Light.ttf
