name: Flutter Deploy

permissions:
  contents: write

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: bluefireteam/flutter-gh-pages@v7
