name: Flutter Deploy

permissions:
  contents: write

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Write env file
        env:
          ENV_DART: ${{ secrets.ENV_DART }}
        run: |
          echo "$ENV_DART" >> ./lib/env.dart

      - name: list dir files
        run: |
          cd lib
          ls

      # I give up on writing the env variable to a file :(
      - name: Write env file
        run: |
          ren ./lib/env.dart.template ./lib/env.dart

      - name: list dir files
        run: |
          cd lib
          ls
